name: PR Title
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
  pull_request_target:
    branches:
      - $default-branch
jobs:
  pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title for Semantic Version Key
        uses: amannn/action-semantic-pull-request@v5
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
